# Backend Fly app configuration
app = "tringo-ai-lab01-url-shortener-api"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
DATABASE_PATH = "/data"
BASE_URL = "https://tringo-ai-lab01-url-shortener-api.fly.dev"

[mounts]
source = "url_db_volume"
destination = "/data"

[[services]]
internal_port = 8000
processes = ["app"]
protocol = "tcp"
script = "check = \"/health\""

[http_service]
internal_port = 8000

[[http_service.checks]]
grace_period = "5s"
interval = "30s"
method = "GET"
path = "/health"
protocol = "http"
timeout = "10s"
type = "http"

[checks.http_service]
grace_period = "5s"
interval = "30s"
method = "GET"
path = "/health"
protocol = "http"
timeout = "10s"
type = "http"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  min_machines_running = 1